# Generated by Django 2.1.15 on 2021-06-13 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=400)),
                ('article', models.TextField()),
                ('summary', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('unique_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newspaper_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('unique_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_name', models.CharField(blank=True, choices=[('N', 'National'), ('S', 'State'), ('C', 'City')], default='N', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='newspaper_name',
            name='preference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newspapers.Preference'),
        ),
        migrations.AddField(
            model_name='news',
            name='newspaper_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_news', to='newspapers.Newspaper_name'),
        ),
    ]
