# Generated by Django 2.1.15 on 2021-06-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
